### ISSUE TITLE
server error atm

### ISSUE THREAD

**Issue by rossmounce** [ropenscilabs/pubpatterns#7]
FYI I'm getting a "server error" at the moment for a JAMA query that I thought previously worked for us.

https://ftdoi.org/api/doi/10.1001/jama.2018.6452/ 
or
curl -v 'https://ftdoi.org/api/doi/10.1001/jama.2018.6452/' | jq

**Comment by sckott** [comment]
thanks for the note, having a look

**Comment by sckott** [comment]
try again now

**Comment by rossmounce** [comment]
working again. thanks!

**Comment by sckott** [comment]
had to fix a too many redirects problem, not surprising unfortunately
